name: hyprpain

description: nothing but pain

base-image: quay.io/fedora-ostree-desktops/base-atomic
image-version: 42

modules:
  - from-file: scripts.yml
  - from-file: packages.yml
  - from-file: fonts.yml
  - from-file: files.yml
  - from-file: remove-packages.yml
  - from-file: services.yml
  - from-file: dotfiles.yml
  - type: signing  



